### ISSUE TITLE
Revocation action plugin should not return an error when certificate is already revoked

### ISSUE THREAD

**Issue by jjalvado** [evertrust/horizon-ansible#5]
When calling the revocation action plugin on an already revoked certificate, Horizon returns an Internal Error with error code '**WEBRA-REVOKE-005**', and the task completes as failed, which is not optimal.

The expected behaviour would be to complete the task with success and potentially indicate that the certificate was already revoked.

**Comment by antoninguyot** [comment]
Closed by #6
